/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Giacomo
 */
public class jFrameOggetti extends javax.swing.JFrame {

    /**
     * Creates new form jFrameOggetti
     */
    public jFrameOggetti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("public class Main {\n    public static void main(String[] args) {\n        NumeriPari NP = new NumeriPari();\n        NP.NumeriPari(); \n    }\n}");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("public static void NumeriPari() {\n     Scanner input = new Scanner(System.in);\n     System.out.print(\"Inserisci il numero di dati da leggere: \");\n     int n = input.nextInt(); // legge il numero di dati da leggere\n     int[] numeri = new int[n]; // crea un array di lunghezza n per i dati\n     System.out.println(\"Inserisci i dati:\");\n     for (int i = 0; i < n; i++) {\n         numeri[i] = input.nextInt(); // legge i dati uno alla volta\n     }\n     System.out.println(\"I numeri pari sono:\");\n      for (int i = 0; i < n; i++) {\n         if (numeri[i] % 2 == 0) {\n         System.out.println(numeri[i]); // stampa solo i numeri pari\n        }\n       }        \n}");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea22.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jTextArea22.setText("Questo metodo legge un numero n di dati da \ninput, quindi crea un array di interi di lunghezza n per\nmemorizzare i dati, successivamente, richiede \nall'utente di inserire i dati uno alla volta e li memorizza \nnell'array.\nPoi il metodo stampa i numeri pari presenti nell'array,\nutilizzando un ciclo for per scorrere tutti gli elementi\ndell'array e un'istruzione condizionale if per verificare se \nun elemento è pari prima di stamparlo sulla console.");
        jScrollPane22.setViewportView(jTextArea22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ESERCIZIO NumeriPari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(jScrollPane22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("ES.1", jPanel1);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("public class Main {\n    public static void main(String[] args) {\n        MultipliDiCinque MC= new MultipliDiCinque();\n        MC.MutripliDiCinque(); \n    }\n}");
        jScrollPane6.setViewportView(jTextArea6);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("    public static void MultipliDiCinque(){\n        for(int i = 1; i <= 100; i++) {\n            if(i % 5 == 0) {\n                System.out.println(i);\n            }\n        }\n    }");
        jScrollPane7.setViewportView(jTextArea7);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ESERCIZIO MultipliDiCinque");

        jTextArea23.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jTextArea23.setText("Il metodo stampa i multipli di cinque compresi tra 1 e 100, per fare ciò, utilizza un ciclo for che parte da 1 e arriva fino a 100,\n incrementando la variabile i ad ogni iterazione.\nAll'interno del ciclo, viene verificato se il valore di i è un multiplo di 5 utilizzando l'operatore modulo (%), che restituisce il resto \ndella divisione tra i e 5. \nSe il resto è 0, allora i è un multiplodi 5 e viene stampato sulla console utilizzando il metodo println().");
        jScrollPane23.setViewportView(jTextArea23);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addGap(80, 80, 80))
        );

        jTabbedPane1.addTab("ES.2", jPanel2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("public static void SommaEMedia(){  //es 10\n    Scanner input = new Scanner(System.in);\n    System.out.print(\"Inserisci il numero di dati da leggere: \");\n     int n = input.nextInt(); // legge il numero di dati da leggere\n     int[] numeri = new int[n]; // crea un array di lunghezza n per i dati\n     System.out.println(\"Inserisci i dati:\");\n     int somma = 0;\n     for (int i = 0; i < n; i++) {\n          numeri[i] = input.nextInt(); // legge i dati uno alla volta\n          somma = somma + numeri[i]; // aggiunge il valore alla somma\n      }\n      double media = somma / n; // calcola la media\n      System.out.println(\"La somma dei dati è: \" + somma);\n      System.out.println(\"La media dei dati è: \" + media);\n }");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("public class Main {\n    public static void main(String[] args) {\n        SommaEMedia SM = new SommaEMedia();\n        SM.SommaEMedia();\n    }\n}");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Il metodo legge un numero n di dati da input e crea un array\n di interi di lunghezza n per memorizzare i dati.\nSuccessivamente, richiede all'utente di inserire i dati uno alla \nvolta e li memorizza nell'array. \nDurante questo processo, il metodo aggiunge il valore di ogni \nelemento alla variabile somma.\nDopo aver memorizzato tutti i dati, il metodo calcola la media \ndei dati dividento la somma totale per il numero di dati. \nLa media viene memorizzata nella variabile media.\nInfine, il metodo stampa la somma dei dati e la media dei dati \nsulla console utilizzando il metodo println() della classe System.");
        jScrollPane5.setViewportView(jTextArea5);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ESERCIZIO SommaEMedia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane1.addTab("ES.3", jPanel3);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("public static void ValoriAssoluti(){\n    Scanner input = new Scanner(System.in);\n    System.out.print(\"Inserisci il numero di dati da leggere: \");\n    int n = input.nextInt(); // legge il numero di dati da leggere\n    System.out.println(\"Inserisci i dati:\");\n     for (int i = 0; i < n; i++) {\n       int in = input.nextInt(); // legge un numero da input\n       int valoreAssoluto = Math.abs(in); // metodo che calcola il valore assoluto\n       System.out.println(\"Il valore assoluto di \" + in + \" è \" + valoreAssoluto);\n     }\n     System.out.println(\"fine programma\");\n}");
        jScrollPane8.setViewportView(jTextArea8);

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("public class Main {\n    public static void main(String[] args) {\n        ValoriAssoluti VA = new ValoriAssoluti();\n        VA.ValoriAssoluti(); \n    }\n}");
        jScrollPane17.setViewportView(jTextArea17);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ESERCIZIO ValoriAssoluti");

        jTextArea24.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jTextArea24.setText("Il metodo ValoriAssoluti() legge un numero n di dati da input e richiede all'utente di inserire i dati uno alla volta. \nPer ogni dato inserito, il metodo calcola il valore assoluto del numero utilizzando il metodo Math.abs(). \nIl valore assoluto di un numero è il valore numerico senza segno, ovvero la distanza del numero dall'origine su \nuna linea numerica.\nUna volta calcolato il valore assoluto del numero, il metodo stampa il risultato sulla console utilizzando il metodo println() \ndella classe System.\nAlla fine del processo, il metodo stampa la stringa \"fine programma\".");
        jScrollPane24.setViewportView(jTextArea24);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ES.4", jPanel4);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jTextArea9.setText("public static void SommaPrimiDieciNumeri(){\n    Scanner input = new Scanner(System.in);\n    boolean inputValido = false;\n    while (!inputValido) {\n        try {\n            System.out.print(\"Inserisci un numero: \");\n            int n = input.nextInt(); // legge un numero da input\n            int somma = 0;\n            for (int i = n + 1; i <= n + 10; i++) {\n                somma = somma + i; // aggiunge il numero alla somma\n            }\n            System.out.println(\"La somma dei primi 10 numeri successivi a \" + n + \" è: \" + somma);\n            inputValido = true;\n        } catch (InputMismatchException e) {\n            System.out.println(\"Errore, inserire un numero intero.\");\n            input.nextLine(); // pulisce il buffer dell'input\n        }\n    }\n}");
        jScrollPane9.setViewportView(jTextArea9);

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jTextArea10.setText("public class Main {\n    public static void main(String[] args) {\n        SommaPrimiDieciNumeri SD \n        = new SommaPrimiDieciNumeri();\n        SD.SommaPrimiDieciNumeri(); \n    }\n}");
        jScrollPane10.setViewportView(jTextArea10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("ESERCIZIO SommaPrimiDieciNumeri");

        jTextArea25.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea25.setColumns(20);
        jTextArea25.setRows(5);
        jTextArea25.setText("Il metodo SommaPrimiDieciNumeri() richiede \nall'utente di inserire un numero intero da input, \nsuccessivamente, il metodo calcola la somma dei \nprimi 10 numeri successivi al numero inserito \nutilizzando un ciclo for.\nSe l'utente inserisce un valore non intero, il metodo\ngestisce l'eccezione di tipo InputMismatchException \ne richiede all'utente di inserire nuovamente il numero.\nAlla fine il metodo stampa il risultato della somma\nsulla console utilizzando il metodo println().");
        jScrollPane25.setViewportView(jTextArea25);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jScrollPane25))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ES.5", jPanel5);

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jTextArea11.setText("    public static void MediaAritmetica(){ \n        Scanner input = new Scanner(System.in);\n        System.out.print(\"Inserisci la quantità di numeri da leggere: \");\n        int n = input.nextInt(); // legge il numero di numeri da leggere\n        double somma = 0;\n        for (int i = 1; i <= n; i++) {\n            System.out.print(\"Inserisci il \" + i + \"° numero: \");\n            double numero = input.nextDouble(); // legge il numero da input\n            somma = somma + numero; // aggiunge il numero alla somma\n        }\n        double media = somma / n; // calcolo della media\n        System.out.println(\"La media dei numeri inseriti è: \" + media);\n    }");
        jScrollPane11.setViewportView(jTextArea11);

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("public class Main {\n    public static void main(String[] args) {\n        MediaAritmetica MA = new MediaAritmetica();\n        MA.MediaAritmetica(); \n    }\n}");
        jScrollPane18.setViewportView(jTextArea18);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("ESERICIZIO MediaAritmetica");

        jTextArea26.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea26.setColumns(20);
        jTextArea26.setRows(5);
        jTextArea26.setText("Il metodo MediaAritmetica() richiede all'utente di inserire un numero n di numeri da input., successivamente, il metodo legge i\nnumeri uno alla volta e li memorizza nella variabile somma, dpodichè calcola la media aritmetica dei numeri inseriti, dividendo la \nsomma dei numeri per il numero di numeri inseriti.\nInfine, il metodo stampa il risultato della media aritmetica sulla console utilizzando il metodo println() della classe System.");
        jScrollPane26.setViewportView(jTextArea26);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane26)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ES.6", jPanel6);

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jTextArea12.setText("public static void Multipli() {\n    Scanner input = new Scanner(System.in);\n    boolean inputValido = false;\n    do {\n        try {\n            System.out.print(\"Inserisci un numero: \");\n            int n = input.nextInt(); // legge un numero da input\n            System.out.println(\"I primi 12 multipli di \" + n + \" sono:\");\n            for (int i = 1; i <= 12; i++) {\n                System.out.println(i * n);\n            }\n            inputValido = true;\n        } catch (InputMismatchException e) {\n            System.out.println(\"L'input inserito non è valido. Riprova.\");\n            input.nextLine(); // pulisce il buffer dell'input\n        }\n    } while (!inputValido);\n}");
        jScrollPane12.setViewportView(jTextArea12);

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("public class Main {\n    public static void main(String[] args) {\n        Multipli Mul= new Multipli();\n        Mul.Multipli(); \n    }\n}");
        jScrollPane19.setViewportView(jTextArea19);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("ESERCIZIO Multipli");

        jScrollPane29.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea29.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea29.setColumns(20);
        jTextArea29.setRows(5);
        jTextArea29.setText("Il metodo Multipli() richiede all'utente di inserire un \nnumero intero da input. Se l'utente inserisce un valore\nnon intero, il metodo gestisce l'eccezione di tipo \nInputMismatchException e richiede all'utente di inserire\nnuovamente il numero, poi il metodo utilizza un ciclo \nfor per stampare i primi 12 multipli del numero inserito.\nAll'interno del ciclo, il metodo moltiplica il numero\ninserito per il valore corrente di i, e stampa il risultato\nsulla console utilizzando il metodo println().");
        jScrollPane29.setViewportView(jTextArea29);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ES.7", jPanel7);

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jTextArea13.setText("public static void CalcolaCubo() {\n    Scanner input = new Scanner(System.in);\n    boolean inputValido = false;\n    do {\n        try {\n            System.out.print(\"Inserisci un numero: \");\n            int numero = input.nextInt(); // legge un numero da input\n            int cubo = numero * numero * numero; // calcola il cubo del numero\n            System.out.println(\"Il cubo di \" + numero + \" è \" + cubo);\n            inputValido = true;\n        } catch (InputMismatchException e) {\n            System.out.println(\"L'input inserito non è valido. Riprova.\");\n            input.nextLine(); // pulisce il buffer dell'input\n        }\n    } while (!inputValido);\n}");
        jScrollPane13.setViewportView(jTextArea13);

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jTextArea20.setText("public class Main {\n    public static void main(String[] args) {\n        CalcolaCubo CC= new CalcolaCubo();\n        CC.CalcolaCubo(); \n    }\n}");
        jScrollPane20.setViewportView(jTextArea20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("ESERCIZIO CalcolaCubo");

        jTextArea30.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea30.setColumns(20);
        jTextArea30.setRows(5);
        jTextArea30.setText("Il metodo CalcolaCubo() richiede all'utente di\ninserire un numero intero da input., se l'utente\ninserisce un valore non intero, il metodo \ngestisce l'eccezione di tipo \nInputMismatchException e richiede \nall'utente di inserire nuovamente il numero,\npoi il metodo calcola il cubo del numero \nutilizzando l'operatore di moltiplicazione (*) \ne stampa il risultato sulla console utilizzando \nil metodo println().");
        jScrollPane30.setViewportView(jTextArea30);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jScrollPane20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(258, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(382, 382, 382))
        );

        jTabbedPane1.addTab("ES.8", jPanel8);

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jTextArea14.setText("public static void DivisoriDiN() {\n    Scanner input = new Scanner(System.in);\n    boolean inputValido = false;\n    do {\n        try {\n            System.out.print(\"Inserisci un numero: \");\n            int n = input.nextInt(); // legge un numero da input\n            System.out.println(\"I divisori di \" + n + \" sono:\");\n            for (int i = 1; i <= n; i++) { // utilizzo un for per creare tutti i numeri compresi tra 1 e n.\n                if (n % i == 0) {      //controllo se tutti numeri precenedeti, compreso n, sono dei divisori traminte il modulo \n                    System.out.println(i);\n                }\n            }\n            inputValido = true;\n        } catch (InputMismatchException e) {\n            System.out.println(\"L'input inserito non è valido. Riprova.\");\n            input.nextLine(); // pulisce il buffer dell'input\n        }\n    } while (!inputValido);\n}");
        jScrollPane14.setViewportView(jTextArea14);

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jTextArea15.setText("public class Main {\n    public static void main(String[] args) {\n        DivisoriDiN DN= new DivisoriDiN();\n        DN.DivisoriDiN(); \n    }\n}");
        jScrollPane15.setViewportView(jTextArea15);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("ESERCIZIO DivisoriDiN");

        jTextArea27.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea27.setColumns(20);
        jTextArea27.setRows(5);
        jTextArea27.setText("Il metodo DivisoriDiN() richiede all'utente di inserire \nun numero intero da input. Se l'utente inserisce un valore \nnon intero, il metodo gestisce l'eccezione e richiede \nall'utente di inserire nuovamente il numero, poi il metodo \nutilizza un ciclo for per creare tutti i numeri compresi tra \n1 e il numero inserito; all'interno del ciclo, il metodo\ncontrolla se il numero è un divisore del numero inserito \nutilizzando il modulo (%), che restituisce il resto della\ndivisione tra il numero inserito e il numero corrente. \nSe il resto è 0, allora il numero corrente è un \ndivisore del numero inserito e viene stampato sulla\n console utilizzando il metodo println().");
        jScrollPane27.setViewportView(jTextArea27);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("ES.9", jPanel9);

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jTextArea16.setText("public static void SommaNumeriNaturali(){\n   Scanner input = new Scanner(System.in);\n   int somma = 0;\n   int numero;\n   do {\n        System.out.print(\"Inserisci un numero naturale, se voui terminare il programma inserisci un numero negativo: \");\n        numero = input.nextInt(); // legge un numero da input\n        if (numero >= 0) {\n           somma = somma + numero; // aggiunge il numero alla somma solo se è positivo\n        }\n    } while (numero >= 0); // continua finché non viene inserito un numero negativo\n    System.out.println(\"La somma dei numeri inseriti è: \" + somma);\n}");
        jScrollPane16.setViewportView(jTextArea16);

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("public class Main {\n    public static void main(String[] args) {\n        DivisoriDiN DN= new DivisoriDiN();\n        DN.DivisoriDiN(); \n    }\n}");
        jScrollPane21.setViewportView(jTextArea21);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("ESERCIZIO SommaNumeriNaturali");

        jTextArea28.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea28.setColumns(20);
        jTextArea28.setRows(5);
        jTextArea28.setText("Il metodo SommaNumeriNaturali() richiede \nall'utente di inserire un numero naturale da \ninput, continua a richiedere all'utente di\ninserire un numero naturale finché non \nviene inserito un numero negativo.\nDurante l'inserimento dei numeri, il metodo\naggiunge ogni numero positivo inserito \nalla variabile somma.\nAlla fine il metodo stampa il risultato della\n somma dei numeri inseriti sulla console \nutilizzando il metodo println() ");
        jScrollPane28.setViewportView(jTextArea28);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(157, 157, 157))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(301, 301, 301))
        );

        jTabbedPane1.addTab("ES.10", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameOggetti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameOggetti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameOggetti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameOggetti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameOggetti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
